version: "3.2"
services:
  fe_market_app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/market"
      - "REACT_APP_BASE_URL=localhost:3000"
      - "API_URL=http://127.0.0.1:8000"
